<?php


date_default_timezone_set('America/Puerto_Rico');
/** Include path **/
ini_set('include_path', ini_get('include_path').';../kat_resources/Classes/PHPExcel/');

/** PHPExcel */
include 'kat_resources/Classes/PHPExcel.php';
/** PHPExcel_Writer_Excel2007 */
include 'kat_resources/Classes/PHPExcel/Writer/Excel2007.php';

include_once("kat_config.php");
include_once("kat_processfunctions.php");


function reportCategories()
{
    
    global $tbl_allcategoriesformenu, $tbl_raw_sitemapcat, $tbl_raw_catforproducts;

    $exactimestamp   = date("Y-m-d H:i:s", microtime(true));
    
    $categories = array();
    $activecatids = array();


    //Active categories
    $sql_activecategories    = "SELECT distinct catid FROM $tbl_raw_catforproducts ORDER by catid;";
    $result_activecategories = mysql_query($sql_activecategories);

             while ($rowactive = mysql_fetch_array($result_activecategories, MYSQL_ASSOC)) {

                $activecatids[] = $rowactive["catid"];
            }



    
    //Grab product qty per category
    //$sql_activecats    = "SELECT id, logicstatus_catmenu, catid, catname  FROM $tbl_allcategoriesformenu WHERE logicstatus_catmenu='off';";
    //Change to use tbl_raw_catforproducts only. Im going to use all categories always
            //REMEMBER TO ADD TOP CATEGORIES Nov 22, 2016! DONE!
    $sql_activecats    = "SELECT * FROM $tbl_raw_sitemapcat ORDER BY catid";
    $result_activecats = mysql_query($sql_activecats);
    $num_oncats        = mysql_num_rows($result_activecats);
    
    if ($num_oncats > 0) {
        
        
        while ($row = mysql_fetch_array($result_activecats, MYSQL_ASSOC)) {
            //Report variables
            $category_id         = $row["id"]; // The id used is the one generated by mysql database
            $name_en             = htmlspecialchars_decode($row["catname"]);
            $columns             = "1"; //What is this for?
            $sort_order          = "0";
            //$date_added          = "2015-09-07 03:14:00";
            $date_added          = "2016-11-22 11:59:00";
            $date_modified       = $exactimestamp;
            $seo_keyword         = ""; //$row["seokeywords"]; <- future version will include
            $description_en      = ""; //$row["catname"]; <- future version will include description
            $meta_title_en       = ""; //$row["metatitle"]; <- future version will include
            $meta_description_en = ""; //$row["metadescription"]; <- future version will include
            $meta_keywords_en    = ""; //$row["metakeywords"]; <- future version will include
            $store_ids           = "0";
            $layout              = "";
            $image_name          = "";
            
            
            //Initialize this variables
            $top       = "false";
            $parent_id = 0;
            $status    = "true";
            
            //Logic variables
            $focalpricecatid = $row["catid"];

            if (in_array($focalpricecatid,$activecatids,true)) {
                    
                    $status = "true";
                    
                } else {
                    $status = "false";
                }
            
            //Debug
            //echo "$focalpricecatid<br>";
            
            //Calculated variables
            if (strlen($focalpricecatid) == 6) {
                $focalpriceparentid = substr($focalpricecatid, 0, 3);
                
            } elseif (strlen($focalpricecatid) == 9) {
                $focalpriceparentid = substr($focalpricecatid, 0, 6);
                
            } elseif (strlen($focalpricecatid) == 12) {
                $focalpriceparentid = substr($focalpricecatid, 0, 9);

            } elseif (strlen($focalpricecatid) == 3) {
                $parent_id = 0;
                $top       = "true";
                $status    = "true";
                
            } else {
            $focalpriceparentid = "none";

            }

            //Debug
            //echo strlen($focalpricecatid)."<br>";
            
            
            //Convert to my Mysql database catid - I will select my id intead of focalprice tbl_raw_sitemapcat
            //$sql_selectmycatid = "SELECT id FROM $tbl_allcategoriesformenu WHERE catid ='$focalpriceparentid';";
            $sql_selectmycatid = "SELECT id FROM $tbl_raw_sitemapcat WHERE catid ='$focalpriceparentid';";
            
            //Debug
            //echo "$sql_selectmycatid<br>";
            
            $result_selectmycatid = mysql_query($sql_selectmycatid);
            $numids               = mysql_num_rows($result_selectmycatid);
            
            //Debug
            //echo "Numid: $numids<br>";
            
            //SET Parent_id for non top categories
            if ($numids > 0) {
                
                while ($row = mysql_fetch_array($result_selectmycatid, MYSQL_ASSOC)) {
                    $parent_id = $row["id"];
                    //Debug
                    //echo "parent_id: $parent_id<br>";
                }
                
            } else {
                
                $parent_id = "0";
                //Debug
                //echo "parent_id: $parent_id<br>"; 
                
            }
            
            
            $onecatcompleted = array(
                "category_id" => $category_id,
                "parent_id" => $parent_id,
                "name(en-gb)" => $name_en,
                "top" => $top,
                "columns" => $columns,
                "sort_order" => $sort_order,
                "image_name" => $image_name,
                "date_added" => $date_added,
                "date_modified" => $date_modified,
                "seo_keyword" => $seo_keyword,
                "description(en-gb)" => $description_en,
                "meta_title(en-gb)" => $meta_title_en,
                "meta_description(en-gb)" => $meta_description_en,
                "meta_keywords(en-gb)" => $meta_keywords_en,
                "store_ids" => $store_ids,
                "layout" => $layout,
                "status" => $status
            );
            
            
            //Debug
            //echo $onecatcompleted."<br><hr>";
            
            
            $Categories[] = $onecatcompleted;
            
        } //while

        $sorted = array_orderby($Categories, 'category_id', SORT_ASC);
            //print_r($sorted);
            //exit;
        
    } //if numcats > 0
    
    return $sorted;
    
} //function reportCategories




function array_orderby()
{
    $args = func_get_args();
    $data = array_shift($args);
    foreach ($args as $n => $field) {
        if (is_string($field)) {
            $tmp = array();
            foreach ($data as $key => $row)
                $tmp[$key] = $row[$field];
            $args[$n] = $tmp;
            }
    }
    $args[] = &$data;
    call_user_func_array('array_multisort', $args);
    return array_pop($args);
}
//************************************************************************************************************************************************************



function categoryExportToExcel(){
global $db_name, $colors, $pathToCategoriesExportFile;

mysql_select_db($db_name);
// Create new PHPExcel object
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["yellow"]."m Create new PHPExcel object\033[0m\r\n";
$objPHPExcel = new PHPExcel();

// Set properties
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["yellow"]."m Set properties\033[0m\r\n";
$objPHPExcel->getProperties()->setCreator("Angel Arcelay");
$objPHPExcel->getProperties()->setLastModifiedBy("Angel Arcelay");
$objPHPExcel->getProperties()->setTitle("Kitblitz Ready MENU for Import");
$objPHPExcel->getProperties()->setSubject("Kitblitz Ready MENU for Import");
$objPHPExcel->getProperties()->setDescription("Kitblitz Ready MENU for Import Office 2007 XLSX, generated using PHP classes.");


// Add some data
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["yellow"]."m Adding some headers\033[0m\r\n";
$objPHPExcel->setActiveSheetIndex(0);

//SET HEADER
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'category_id');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'parent_id');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'name(en-gb)');
$objPHPExcel->getActiveSheet()->SetCellValue('D1', 'top');

$objPHPExcel->getActiveSheet()->SetCellValue('E1', 'columns');
$objPHPExcel->getActiveSheet()->SetCellValue('F1', 'sort_order');
$objPHPExcel->getActiveSheet()->SetCellValue('G1', 'image_name');
$objPHPExcel->getActiveSheet()->SetCellValue('H1', 'date_added');

$objPHPExcel->getActiveSheet()->SetCellValue('I1', 'date_modified');
$objPHPExcel->getActiveSheet()->SetCellValue('J1', 'seo_keyword');
$objPHPExcel->getActiveSheet()->SetCellValue('K1', 'description(en-gb)');
$objPHPExcel->getActiveSheet()->SetCellValue('L1', 'meta_title(en-gb)');

$objPHPExcel->getActiveSheet()->SetCellValue('M1', 'meta_description(en-gb)');
$objPHPExcel->getActiveSheet()->SetCellValue('N1', 'meta_keywords(en-gb)');
$objPHPExcel->getActiveSheet()->SetCellValue('O1', 'store_ids');
$objPHPExcel->getActiveSheet()->SetCellValue('P1', 'layout');
$objPHPExcel->getActiveSheet()->SetCellValue('Q1', 'status');

//SET FONT IN BOLD LIKE A HEADER
$objPHPExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("B1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("C1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("D1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("E1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("F1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("G1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("H1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("I1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("J1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("K1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("L1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("M1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("N1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("O1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("P1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("Q1")->getFont()->setBold(true);

echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["yellow"]."m Adding Menu Categories...\033[0m\r\n";
$sheet=reportCategories();
/*echo "<pre>";
echo var_dump($sheet);
echo "</pre>";
exit();*/
$objPHPExcel->getActiveSheet()->fromArray($sheet, NULL, 'A2');

// Rename sheet
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["yellow"]."m Rename sheet\033[0m\r\n";
$objPHPExcel->getActiveSheet()->setTitle('Categories');

		
// Save Excel 2007 file
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["yellow"]."m Write to Excel2007 format\033[0m\r\n";
$dateforfilename = date("Y-m-d-H-i-s", microtime(true));
$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
//$objWriter->save(str_replace('.php', '.xlsx', __FILE__));

$filename = "CatoMenu-$dateforfilename.xlsx";
$objWriter->save($pathToCategoriesExportFile.$filename);
//system('open ' .$pathToCategoriesExportFile);
// Echo done
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["yellow"]."m Done writing:\033[".$colors["light_cyan"]."m $pathToCategoriesExportFile$filename\033[0m \r\n"; 
 
echo "\033[".$colors["light_gray"]."m CATEGORY EXPORT Completed. \033[0m \r\n\r\n";

mysql_close();


} // End of categoryExportToExcel


function productsExportToExcel(){

    global $db_name, $colors, $pathToProductExportFile, $tbl_raw_productdetails;

mysql_select_db($db_name);

//Products to include in this Export
$sql_Products = "SELECT * FROM $tbl_raw_productdetails WHERE logicstatus_proddetails <> 'no data error' ORDER by id;"; 

echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["light_yellow"]."m PRODUCTS DATA EXPORT PROCESS STARTED\033[0m\r\n";
//END: Range process

//PRODUCT DATA ACQUISITION
list($prodqty, $sheetProducts)=reportProducts($sql_Products);
//*************************************************************
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["light_yellow"]."m Quantity of Products included: $prodqty\033[0m\r\n";
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["light_yellow"]."m Preparing info for Additional Image sheet...\033[0m\r\n";

//IMAGES DATA ACQUISITION
$sheetAdditionalImages=AdditionalImages($sql_Products);
//*************************************************************

// Create new PHPExcel object
//echo date("Y-m-d H:i:s", microtime(true)) . " Create new PHPExcel object<br>";
echo "\r\n". date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["light_yellow"]."m Create new PHPExcel object\033[0m\r\n";
$objPHPExcel = new PHPExcel();

// Set properties
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["light_yellow"]."m Set properties\033[0m\r\n";
$objPHPExcel->getProperties()->setCreator("Angel Arcelay");
$objPHPExcel->getProperties()->setLastModifiedBy("Angel Arcelay");
$objPHPExcel->getProperties()->setTitle("Kitblitz Ready Data for Import");
$objPHPExcel->getProperties()->setSubject("Kitblitz Ready Data for Import");
$objPHPExcel->getProperties()->setDescription("Kitblitz Ready Data for Import Office 2007 XLSX, generated using PHP classes.");

// Creating Sheets
 $titles = array('Products', 'AdditionalImages', 'Specials', 'Discounts', 'Rewards', 'ProductOptions', 'ProductOptionValues', 'ProductAttributes', 'ProductFilters');
$sheet = 0;
foreach($titles as $key=>$value){
    if($key > 0){
        $objPHPExcel->createSheet();
        $sheet = $objPHPExcel->setActiveSheetIndex($key);
        $sheet->setTitle("$value");
         echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["light_yellow"]."m Sheet $value created.\033[0m\r\n";
        //Do you want something more here
    }else{
        $objPHPExcel->setActiveSheetIndex(0)->setTitle("$value");
        echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["light_yellow"]."m Sheet $value created.\033[0m\r\n";
    }
    
}  

//Adding Headers
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["light_yellow"]."m Adding headers...\033[0m\r\n";
//PRODUCT SHEET @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
$objPHPExcel->setActiveSheetIndex(0);

//SET HEADER
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'product_id');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'name(en-gb)');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'categories');
$objPHPExcel->getActiveSheet()->SetCellValue('D1', 'sku');

$objPHPExcel->getActiveSheet()->SetCellValue('E1', 'upc');
$objPHPExcel->getActiveSheet()->SetCellValue('F1', 'ean');
$objPHPExcel->getActiveSheet()->SetCellValue('G1', 'jan');
$objPHPExcel->getActiveSheet()->SetCellValue('H1', 'isbn');

$objPHPExcel->getActiveSheet()->SetCellValue('I1', 'mpn');
$objPHPExcel->getActiveSheet()->SetCellValue('J1', 'location');
$objPHPExcel->getActiveSheet()->SetCellValue('K1', 'quantity');
$objPHPExcel->getActiveSheet()->SetCellValue('L1', 'model');

$objPHPExcel->getActiveSheet()->SetCellValue('M1', 'manufacturer');
$objPHPExcel->getActiveSheet()->SetCellValue('N1', 'image_name');
$objPHPExcel->getActiveSheet()->SetCellValue('O1', 'shipping');
$objPHPExcel->getActiveSheet()->SetCellValue('P1', 'price');

$objPHPExcel->getActiveSheet()->SetCellValue('Q1', 'points');
$objPHPExcel->getActiveSheet()->SetCellValue('R1', 'date_added');
$objPHPExcel->getActiveSheet()->SetCellValue('S1', 'date_modified');
$objPHPExcel->getActiveSheet()->SetCellValue('T1', 'date_available');

$objPHPExcel->getActiveSheet()->SetCellValue('U1', 'weight');
$objPHPExcel->getActiveSheet()->SetCellValue('V1', 'weight_unit');
$objPHPExcel->getActiveSheet()->SetCellValue('W1', 'length');
$objPHPExcel->getActiveSheet()->SetCellValue('X1', 'width');

$objPHPExcel->getActiveSheet()->SetCellValue('Y1', 'height');
$objPHPExcel->getActiveSheet()->SetCellValue('Z1', 'length_unit');
$objPHPExcel->getActiveSheet()->SetCellValue('AA1', 'status');
$objPHPExcel->getActiveSheet()->SetCellValue('AB1', 'tax_class_id');

$objPHPExcel->getActiveSheet()->SetCellValue('AC1', 'seo_keyword');
$objPHPExcel->getActiveSheet()->SetCellValue('AD1', 'description(en-gb)');
$objPHPExcel->getActiveSheet()->SetCellValue('AE1', 'meta_title(en-gb)');
$objPHPExcel->getActiveSheet()->SetCellValue('AF1', 'meta_description(en-gb)');

$objPHPExcel->getActiveSheet()->SetCellValue('AG1', 'meta_keywords(en-gb)');
$objPHPExcel->getActiveSheet()->SetCellValue('AH1', 'stock_status_id');
$objPHPExcel->getActiveSheet()->SetCellValue('AI1', 'store_ids');
$objPHPExcel->getActiveSheet()->SetCellValue('AJ1', 'layout');

$objPHPExcel->getActiveSheet()->SetCellValue('AK1', 'related_ids');
$objPHPExcel->getActiveSheet()->SetCellValue('AL1', 'tags(en-gb)');
$objPHPExcel->getActiveSheet()->SetCellValue('AM1', 'sort_order');
$objPHPExcel->getActiveSheet()->SetCellValue('AN1', 'subtract');

$objPHPExcel->getActiveSheet()->SetCellValue('AO1', 'minimum');

//SET FONT IN BOLD LIKE A HEADER
$objPHPExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("B1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("C1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("D1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("E1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("F1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("G1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("H1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("I1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("J1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("K1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("L1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("M1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("N1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("O1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("P1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("Q1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("R1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("S1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("T1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("U1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("V1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("X1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("Y1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("Z1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("AA1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AB1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AC1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AD1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("AE1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AF1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AG1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AH1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("AI1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AJ1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AK1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AL1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("AM1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AN1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("AO1")->getFont()->setBold(true);



// Rename sheet
//echo date("Y-m-d H:i:s", microtime(true)) . " Rename sheet to Products<br>";
//$objPHPExcel->getActiveSheet()->setTitle('Products');

//@@@@@@@@@@ PRODUCT SHEET END SHEET CREATION @@@@@@@@@@@@@@@@@@@@@@@


//ADDITIONAL IMAGES SHEET @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

$objPHPExcel->setActiveSheetIndex(1);

//SET HEADER
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'product_id');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'image');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'sort_order');


//SET FONT IN BOLD LIKE A HEADER
$objPHPExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("B1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("C1")->getFont()->setBold(true);

// Rename sheet
//echo date("Y-m-d H:i:s", microtime(true)) . " Rename sheet to AdditionalImages<br>";
//$objPHPExcel->getActiveSheet()->setTitle('AdditionalImages');

//@@@@@@@@@@ PRODUCT SHEET END SHEET CREATION @@@@@@@@@@@@@@@@@@@@@@@



//SPECIALS SHEET @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
$objPHPExcel->setActiveSheetIndex(2);

//SET HEADER
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'product_id');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'customer_group');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'priority');
$objPHPExcel->getActiveSheet()->SetCellValue('D1', 'price');

$objPHPExcel->getActiveSheet()->SetCellValue('E1', 'date_start');
$objPHPExcel->getActiveSheet()->SetCellValue('F1', 'date_end');


//SET FONT IN BOLD LIKE A HEADER
$objPHPExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("B1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("C1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("D1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("E1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("F1")->getFont()->setBold(true);


// Rename sheet
//echo date("Y-m-d H:i:s", microtime(true)) . " Rename sheet to Specials<br>";
//$objPHPExcel->getActiveSheet()->setTitle('Specials');

//@@@@@@@@@@ SPECIALS SHEET END SHEET CREATION @@@@@@@@@@@@@@@@@@@@@@@


//DISCOUNTS SHEET @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
$objPHPExcel->setActiveSheetIndex(3);

//SET HEADER
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'product_id');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'customer_group');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'quantity');
$objPHPExcel->getActiveSheet()->SetCellValue('D1', 'priority');

$objPHPExcel->getActiveSheet()->SetCellValue('E1', 'price');
$objPHPExcel->getActiveSheet()->SetCellValue('F1', 'date_start');
$objPHPExcel->getActiveSheet()->SetCellValue('G1', 'date_end');

//SET FONT IN BOLD LIKE A HEADER
$objPHPExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("B1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("C1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("D1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("E1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("F1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("G1")->getFont()->setBold(true);

// Rename sheet
//echo date("Y-m-d H:i:s", microtime(true)) . " Rename sheet to Discounts<br>";
//$objPHPExcel->getActiveSheet()->setTitle('Discounts');

//@@@@@@@@@@ DISCOUNTS SHEET END SHEET CREATION @@@@@@@@@@@@@@@@@@@@@@@




//REWARDS SHEET @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
$objPHPExcel->setActiveSheetIndex(4);

//SET HEADER
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'product_id');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'customer_group');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'points');


//SET FONT IN BOLD LIKE A HEADER
$objPHPExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("B1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("C1")->getFont()->setBold(true);


// Rename sheet
//echo date("Y-m-d H:i:s", microtime(true)) . " Rename sheet to Rewards<br>";
//$objPHPExcel->getActiveSheet()->setTitle('Rewards');

//@@@@@@@@@@ REWARDS SHEET END SHEET CREATION @@@@@@@@@@@@@@@@@@@@@@@

//PRODUCT OPTIONS SHEET @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
$objPHPExcel->setActiveSheetIndex(5);

//SET HEADER
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'product_id');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'option_id');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'default_option_value');
$objPHPExcel->getActiveSheet()->SetCellValue('D1', 'required');


//SET FONT IN BOLD LIKE A HEADER
$objPHPExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("B1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("C1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("D1")->getFont()->setBold(true);

// Rename sheet
//echo date("Y-m-d H:i:s", microtime(true)) . " Rename sheet to ProductOptions<br>";
//$objPHPExcel->getActiveSheet()->setTitle('ProductOptions');

//@@@@@@@@@@ PRODUCT OPTIONS SHEET END SHEET CREATION @@@@@@@@@@@@@@@@@@@@@@@

                                        

//PRODUCT OPTION VALUES SHEET @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
$objPHPExcel->setActiveSheetIndex(6);

//SET HEADER
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'product_id');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'option_id');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'option_value_id');
$objPHPExcel->getActiveSheet()->SetCellValue('D1', 'quantity');

$objPHPExcel->getActiveSheet()->SetCellValue('E1', 'subtract');
$objPHPExcel->getActiveSheet()->SetCellValue('F1', 'price');
$objPHPExcel->getActiveSheet()->SetCellValue('G1', 'price_prefix');
$objPHPExcel->getActiveSheet()->SetCellValue('H1', 'points');

$objPHPExcel->getActiveSheet()->SetCellValue('I1', 'points_prefix');
$objPHPExcel->getActiveSheet()->SetCellValue('J1', 'weight');
$objPHPExcel->getActiveSheet()->SetCellValue('K1', 'weight_prefix');


//SET FONT IN BOLD LIKE A HEADER
$objPHPExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("B1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("C1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("D1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("E1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("F1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("G1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("H1")->getFont()->setBold(true);

$objPHPExcel->getActiveSheet()->getStyle("I1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("J1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("K1")->getFont()->setBold(true);


// Rename sheet
//echo date("Y-m-d H:i:s", microtime(true)) . " Rename sheet to ProductsOptionValues<br>";
//$objPHPExcel->getActiveSheet()->setTitle('ProductsOptionValues');

//@@@@@@@@@@ PRODUCT OPTION VALUES SHEET END SHEET CREATION @@@@@@@@@@@@@@@@@@@@@@@


//PRODUCT ATTRIBUTES SHEET @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
$objPHPExcel->setActiveSheetIndex(7);

//SET HEADER
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'product_id');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'attribute_group_id');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'attribute_id');
$objPHPExcel->getActiveSheet()->SetCellValue('D1', 'text(en-gb)');


//SET FONT IN BOLD LIKE A HEADER
$objPHPExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("B1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("C1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("D1")->getFont()->setBold(true);


// Rename sheet
//echo date("Y-m-d H:i:s", microtime(true)) . " Rename sheet to ProductsAttributes<br>";
//$objPHPExcel->getActiveSheet()->setTitle('ProductsAttributes');

//@@@@@@@@@@ PRODUCT ATTRIBUTES SHEET END SHEET CREATION @@@@@@@@@@@@@@@@@@@@@@@

//PRODUCT FILTERS SHEET @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
$objPHPExcel->setActiveSheetIndex(8);

//SET HEADER
$objPHPExcel->getActiveSheet()->SetCellValue('A1', 'product_id');
$objPHPExcel->getActiveSheet()->SetCellValue('B1', 'filter_group_id');
$objPHPExcel->getActiveSheet()->SetCellValue('C1', 'filter_id');


//SET FONT IN BOLD LIKE A HEADER
$objPHPExcel->getActiveSheet()->getStyle("A1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("B1")->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle("C1")->getFont()->setBold(true);


// Rename sheet
//echo date("Y-m-d H:i:s", microtime(true)) . " Rename sheet to ProductFilters<br>";
//$objPHPExcel->getActiveSheet()->setTitle('ProductFilters');

//@@@@@@@@@@ PRODUCT FILTERS SHEET END SHEET CREATION @@@@@@@@@@@@@@@@@@@@@@@

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


//Insert all Products at once

//Insert products
$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->fromArray($sheetProducts, NULL, 'A2');

//Insert Images
$objPHPExcel->setActiveSheetIndex(1);
$objPHPExcel->getActiveSheet()->fromArray($sheetAdditionalImages, NULL, 'A2');

$objPHPExcel->setActiveSheetIndex(0);

// Save Excel 2007 file
echo date("Y-m-d H:i:s", microtime(true)) . " \033[".$colors["light_yellow"]."m Write to Excel2007 format\033[0m\r\n";
$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
//$objWriter->save(str_replace('.php', '.xlsx', __FILE__));
$dateforfilename = date("Y-m-d-H-i-s", microtime(true));


$filename = "ForImport-$dateforfilename-$prodqty.xlsx";
$objWriter->save($pathToProductExportFile.$filename);
//system('open '.$pathToProductExportFile);
// Echo done
echo date("Y-m-d H:i:s", microtime(true)) . " Done writing:\033[".$colors["light_cyan"]."m $pathToProductExportFile$filename\033[0m\r\n"; 

// Echo done
//echo date("Y-m-d H:i:s", microtime(true)) . " Done writing file: $filename";


}





function reportProducts($sql_Products){

    global $colors, $tbl_allcategoriesformenu, $tbl_raw_sitemapcat, $tbl_raw_catforproducts, $tbl_raw_productdetails, $tbl_raw_pricehistory, $tbl_raw_imagesloc;
    global $pathtoimage, $markupvalue, $paypalfee, $paypalpercent, $markup153, $markup153plus;

 
    $exactimestamp       = date("Y-m-d H:i:s", microtime(true));

//ARRAY INITIATION    
    $Products            = array();
    $Categories_list     = array();//to put all categories comma delimited to place string in $categories variable
    

//PRODUCT REPORT VARIABLES INITIATION 
    $product_id          = "";
    $name_en             = "";
    $categories          = "";
    $sku                 = "";
    $upc                 = "";
    $ean                 = "";
    $jan                 = "";
    $isbn                = "";
    $mpn                 = "";
    $location            = "";
    $quantity            = "1000";
    $model               = "";
    $manufacturer        = "";
    $image_name          = "";
    $shipping            = "yes";
    $price               = "";
    $points              = "0";
    $date_added          = $exactimestamp;
    $date_modified       = $exactimestamp;
    $date_available      = "";
    $weight              = "0.00";
    $weight_unit         = "kg";
    $length              = "0";
    $width               = "0";
    $height              = "0";
    $length_unit         = "cm";
    $status              = "true";
    $tax_class_id        = "0";
    $seo_keyword         = "";
    $description_en      = "";
    $meta_title_en       = "";
    $meta_description_en = "";
    $meta_keywords_en    = "";
    $stock_status_id     = ""; //5-SOLD OUT ,6-(2 - 3 Days),7-In Stock ,8-PREORDER
    $store_ids           = "0";
    $layout              = "";
    $related_ids         = "";
    $tags_en             = "";
    $sort_order          = "0";
    $subtract            = "false";
    $minimum             = "1";


    //Grab ALL PRODUCTS
    //$sql_Products        = "SELECT * FROM $tbl_raw_productdetails WHERE logicstatus_proddetails <> 'no data error' AND id >= $from AND id <= $to ORDER by id";
    
    $result_Products     = mysql_query($sql_Products);
    $num_Products        = mysql_num_rows($result_Products);
    

//echo "num_Products: $num_Products";

    if ($num_Products > 0) {

         //Header
            //echo "~Id~SKU~Markupvalue~Rawprofit~Profit~Cost~SellingPrice~Sweetprice~\r\n";
$iteractions=1;
        while ($rowProd = mysql_fetch_array($result_Products, MYSQL_ASSOC)) {

            //PRODUCT DETAILS
            $product_id                 = $rowProd["id"];
            $sku                        = $rowProd["sku"]; //sku field
            //$skufordb                   = "KBZ".$sku; //This will be used for kitblitz. Not the same as focalprice
            $productname                = $rowProd["productname"]; //name field
            $summary                    = $rowProd["summary"]; 
            $description                = $rowProd["description"]; //description field

            $model               = "KBZ".$sku;

            $metax = $model ." ". $productname;

            $meta_title_en  = $metax;     
            $meta_description_en = $metax;  
            $meta_keywords_en    = $metax;  
            
            //stock_status_id field
            $stock_allowBuy             = $rowProd["stock_allowBuy"]; //status field

             //5-SOLD OUT ,6-(2 - 3 Days),7-In Stock ,8-PREORDER
           if ($stock_allowBuy=="True"){

            $stock_status_id = 7;

           } else {

            $stock_status_id = 5;

           }

            //Debug
            /*
            echo " product_id    : $product_id<br>";
            echo " sku           : $sku<br>";
            echo " productname   : $productname<br>";
            echo " stock_allowBuy: $stock_allowBuy<br>";
            */
            
            //PRICE HISTORY
            $sql_Price        = "SELECT  MarketPrice, UnitPrice FROM $tbl_raw_pricehistory WHERE sku = '$sku' ORDER by id DESC LIMIT 1;";
            $result_Price     = mysql_query($sql_Price);
            $rowPrice = mysql_fetch_array($result_Price, MYSQL_ASSOC);
            
            $UnitPrice = $rowPrice["UnitPrice"];
            $MarketPrice = $rowPrice["MarketPrice"];
            
            $currcostprice            = max($UnitPrice, $UnitPrice);

             //Debug
            //echo "currcostprice    : $currcostprice, ";
            
            /*
            //Calcule my price
            $newretailprice = ($currcostprice + $paypalfee + ($currcostprice*$paypalpercent));

            if ($currcostprice<=153){
                $markupvalue = $markup153;
            } else {
                $markupvalue = $markup153plus;
            }

            $markuppercentage = ((100-$markupvalue)/100);
            //price field
            $newsellingprice = ($newretailprice/$markuppercentage);
            $newsellingprice=number_format($newsellingprice, 2, '.', '');
            */

            //Calcule my price - Sweet price calculation Prime numbers will be as is other .99
            $newretailprice = ($currcostprice + $paypalfee + ($currcostprice*$paypalpercent));

            /*
            if ($currcostprice<=153){
                $markupvalue = $markup153;
            } else {
                $markupvalue = $markup153plus;
            }
            */
/*
            if ($currcostprice>0 && $currcostprice<=153){
                $markupvalue = (-.1438*$currcostprice)+35;
            } elseif ($currcostprice>0 && $currcostprice>153) {
                $markupvalue = 13;
            }
*/

 if ($currcostprice>0 && $currcostprice<=153){
                $markupvalue = 20;
            } elseif ($currcostprice>0 && $currcostprice>153) {
                $markupvalue = 12.5;
            }


            $markuppercentage = ((100-$markupvalue)/100);
           
            $roundsellingprice = $ceilsellingprice = $newsellingprice = ($newretailprice/$markuppercentage);
            

            $ceilsellingprice = ceil($ceilsellingprice);
            $roundsellingprice = round($roundsellingprice);

            $difference = $ceilsellingprice - $newsellingprice;

            
            
            if (isPrime($newsellingprice))
                {
                
                $sweetprice=number_format($newsellingprice, 2, '.', '');

                } else {

                $sweetprice = $newsellingprice + ($difference - .01);
                $sweetprice=number_format($sweetprice, 2, '.', '');

                }

    
                $rawprofit = $sweetprice-$currcostprice;
                $rawprofit=number_format($rawprofit, 2, '.', '');
                $profit = $sweetprice-$newretailprice;
                $profit=number_format($profit, 2, '.', '');

            //Debug
            //echo "Id: $product_id\tsku($sku)\tmv($markupvalue)\trawprofit($rawprofit)\t\tprofit($profit)\tCost: $currcostprice\t";
            //echo ":::Selling-Price: ". number_format($newsellingprice, 2, '.', '')."\t-> Sweet-price: $sweetprice\r\n";

               
            
            //Row data
            //echo "~$product_id~$sku~$markupvalue~$rawprofit~$profit~$currcostprice~".number_format($newsellingprice, 2, '.', '')."~$sweetprice~\r\n";
           
           //Progress
           show_status($colors["light_purple"],"PRODUCT EXPORT PROCESS",$iteractions, $num_Products, $size=30);
           
           
           $iteractions++;

           //IMAGES
            $pathtoimage = "catalog/productsimages/";
            $sql_Ima        = "SELECT  imaurl FROM $tbl_raw_imagesloc WHERE sku = '$sku' AND priorityima = 1;";
            $result_Ima   = mysql_query($sql_Ima);
            $rowIma = mysql_fetch_array($result_Ima, MYSQL_ASSOC);
            
            $imaurl_Ima                 = $rowIma["imaurl"];

            $fileinfo=pathinfo($imaurl_Ima);
            $filename=$fileinfo['basename'];
            
            //image_name field
            $filenameImageforExcel = $pathtoimage.$filename;
            
            //Debug
            //echo "filenameImageforExcel    : $filenameImageforExcel<br>";
             

             //Product Cat Ids from Online Focalprice
            $sql_Cats       = "SELECT  catid FROM $tbl_raw_catforproducts WHERE sku = '$sku'";
            $result_Cats   = mysql_query($sql_Cats);
        

                    //Categories field

                    while ($rowCats = mysql_fetch_array($result_Cats, MYSQL_ASSOC)) {
                        $catid = $rowCats["catid"];
                        $sql_NewCatid    = "SELECT id FROM $tbl_raw_sitemapcat WHERE catid = '$catid';";
                        $result_NewCatid = mysql_query($sql_NewCatid);
                        $rowNewCatid     = mysql_fetch_array($result_NewCatid, MYSQL_ASSOC);
                            $newid = $rowNewCatid["id"];
                           
                            //Debug
                            //echo "newid = $newid<br>";
                            $Categories_list[]=$newid;

                            //Debug
                            //echo "<pre>";
                            //print_r($Categories_list);
                            //echo "</pre>";

                    }

                    //Categories field
                    $Categories_list=array_values(array_filter($Categories_list));
                    $categories = implode(',', $Categories_list);
                    
                    //Debug
                    //echo "categories = $categories<br>";
            
           //Push into Products array
            $Products[] = array( 
                "product_id"            => $product_id, //impacted
                "name(en-gb)"           => $productname, //impacted
                "categories"            => $categories, //impacted
                "sku"                   => $sku, //impacted
                "upc"                   => $upc,
                "ean"                   => $ean,
                "jan"                   => $jan,
                "isbn"                  => $isbn,
                "mpn"                   => $mpn,
                "location"              => $location,
                "quantity"              => $quantity, //impacted
                "model"                 => $model, //$model,
                "manufacturer"          => $manufacturer,
                "image_name"            => $filenameImageforExcel, //impacted
                "shipping"              => $shipping, //impacted 
                "price"                 => $sweetprice, ////impacted changed from $newsellingprice to $sweetprice  
                "points"                => $points,
                "date_added"            => $date_added, //impacted
                "date_modified"         => $date_modified, //impacted
                "date_available"        => $date_available, //impacted
                "weight"                => $weight,
                "weight_unit"           => $weight_unit,
                "length"                => $length,
                "width"                 => $width,
                "height"                => $height,
                "length_unit"           => $length_unit,
                "status"                => $status, //impacted
                "tax_class_id"          => $tax_class_id,
                "seo_keyword"           => $seo_keyword,
                "description(en-gb)"       => $description, //impacted
                "meta_title(en-gb)"        => $meta_title_en,
                "meta_description(en-gb)"  => $meta_description_en,
                "meta_keywords(en-gb)"     => $meta_keywords_en,
                "stock_status_id"       => $stock_status_id, //impacted
                "store_ids"             => $store_ids, //impacted
                "layout"                => $layout,
                "related_ids"           => $related_ids,
                "tags(en-gb)"              => $tags_en,
                "sort_order"            => $sort_order,
                "subtract"              => $subtract, //impacted
                "minimum"               => $minimum //impacted
            );

unset($Categories_list);
}//while
    }//$num_Products


            //Set categories ok
            //Set First Image -  ok
            //Set last calculated price ok
            //Set Stock Status Id - Investigate all ids
            /*$categories = ""; ok
            $image_name  = ""; ok
            $price = ""; ok
            $stock_status_id = "";
            $status = "";*/
           
return array($num_Products, $Products);
}//function reportProducts
//************************************************************************************************************************************************************

 
 
function AdditionalImages($sql_Products){
 
 global  $colors, $tbl_raw_imagesloc, $tbl_raw_productdetails, $pathtoimage;
 $AdditionalImagesSheet = array();

//Grab ALL PRODUCTS - Here received the sql
     $result_Products     = mysql_query($sql_Products);
    $num_Products        = mysql_num_rows($result_Products);
    
$iteractions=1;
        while ($row_AllProducts = mysql_fetch_array($result_Products, MYSQL_ASSOC)) {
               
                $product_id = $row_AllProducts["id"];
                $sku = $row_AllProducts["sku"];


                $sqlImages = "SELECT id, imaurl, priorityima FROM $tbl_raw_imagesloc WHERE sku = '$sku' AND priorityima <> 1  ORDER BY id;";
                $resultsImages = mysql_query($sqlImages);
               
                                while ($rowImages =  mysql_fetch_array($resultsImages, MYSQL_ASSOC)){
                                //sort_order field
                                $sort_order = $rowImages['priorityima'];

                                //image field
                                $id = $rowImages['id'];
                                $imageurl = $rowImages['imaurl'];
                                $fileinfo=pathinfo($imageurl);
                                $image=$fileinfo['basename'];
                                
                                //image_name field
                                $pathfilename = $pathtoimage.$image;
                                
                               //echo "$id - [$sku]\t-> $image\r\n";
                                                $AdditionalImagesSheet[] = array(
                                               
                                                "product_id" => $product_id,
                                                "image" => $pathfilename,
                                                "sort_order" => $sort_order
                                               
                                                    );
                               
                                } //while images

        show_status($colors["light_cyan"],"IMAGES LOCATION TO EXCEL",$iteractions, $num_Products, $size=30);

           $iteractions++;

 
} //while
 
 
return $AdditionalImagesSheet;
} //End AdditionalImages
 
 
function isPrime($n) {
$i = 2;
if ($n == 2) {
return true;
}
$sqrtN = sqrt($n);
while ($i <= $sqrtN) {
if ($n % $i == 0) {
return false;
}
$i++;
}
return true;
}


function prepareUpload(){

global $pathimagestoUpload, $ZipfileSaveFolder;

$callTime = microtime(true);
$timestamp=timehumanread($callTime);

$zipfilename = "imagesforUpload-$timestamp.zip";
        

        if(extension_loaded('zip')){
        Zip($pathimagestoUpload, $ZipfileSaveFolder.$zipfilename);

        }

}


/*
Products
AdditionalImages
Special
Discounts
Rewards
ProductOptions
ProductValues
ProductAttributes
*/

?>